services:
  deps:
    image: deps
    build:
      context: .
      dockerfile: ./deps.dockerfile

  graphql:
    build:
      context: .
      dockerfile: ./graphql/cmd.dockerfile
    depends_on:
      - deps
      - account
    expose:
      - "9100"
    ports:
      - "9100:9100"
    environment:
      GRAPHQL_PORT: 9100
      ACCOUNT_SERVICE_URL: account:9100
      GRAPHQL_DEPLOYMENT: docker
      GRAPHQL_RELEASE: 1
      GRAPHQL_VERSION: v0.0.1
    volumes:
      - ./:/services
    networks:
      - coconet
    restart: on-failure

  account:
    build:
      context: .
      dockerfile: ./account/cmd.dockerfile
    depends_on:
      - deps
      - account_db
    expose:
      - "9100"
    ports:
      - "9099:9100"
    environment:
      ACCOUNT_PORT: 9100
      ACCOUNT_DSN: postgres://cocopuff:123456@account_db/cocopuff?sslmode=disable
      ACCOUNT_DEPLOYMENT: docker
      ACCOUNT_RELEASE: 1
      ACCOUNT_VERSION: v0.0.1
    volumes:
      - ./:/services
    networks:
      - coconet
    restart: on-failure

  account_db:
    build:
      context: ./account
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: cocopuff
      POSTGRES_USER: cocopuff
      POSTGRES_PASSWORD: 123456
    networks:
      - coconet
    restart: unless-stopped

networks:
  coconet:
    external:
      name: coconet
